version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cryptox_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cryptox
      POSTGRES_USER: cryptox_user
      POSTGRES_PASSWORD: cryptox_password_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryptox_user -d cryptox"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cryptox_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: